### ISSUE TITLE
VM838 display.js:331 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '[object HTMLBodyElement]' is not a valid selector.

### ISSUE THREAD

**Issue by JZLeung** [arguiot/DisplayJS#24]
when i try to use `$.scrollTop()`.
```
$.scrollTop()

23:29:45.660 VM838 display.js:331 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '[object HTMLBodyElement]' is not a valid selector.
    at DisplayJS.select (http://localhost:8000/node_modules/display.js/dist/display.js:331:52)
    at DisplayJS.s (http://localhost:8000/node_modules/display.js/dist/display.js:343:16)
    at DisplayJS.scrollTop (http://localhost:8000/node_modules/display.js/dist/display.js:393:14)
    at <anonymous>:1:3
```

**Comment by arguiot** [comment]
I’ll try to fix that. Thanks for reporting the bug 🐜

**Comment by arguiot** [comment]
It has been fixed in the latest commit, I'll release this version soon, I just need to see if there is some other bugs.
